### ISSUE TITLE
NameError: name 'lastPoint' is not defined

### ISSUE THREAD

**Issue by jmcollin78** [markcocker/influxdb-query-to-sensor#1]
Hello, I try to use your marvellous Python script but I always get this error when execution all of my requests: 

```
2022-01-30 23:30:27 ERROR (MainThread) [custom_components.pyscript.apps.influxdb_query_to_entity.influxdb_query_to_entity] Exception in <apps.influxdb_query_to_entity.influxdb_query_to_entity> line 133:
        state.set(entity_id, value=lastPoint, new_attributes=attributes)
                                   ^
NameError: name 'lastPoint' is not defined
```

And I can't get ir dof this.

My request is the following:
```
service: pyscript.influxdb_query_to_entity
data:
  database: hadb
  query: >-
    SELECT mean("value") FROM "temperature_salon" WHERE time > now() - 30d
    GROUP BY time(30m) FILL(none)
  key_field_name: time
  value_field_name: mean
  entity_id: sensor.temperature_salon_30j
  unit_of_measurement: "°C"
  friendly_name: "Température salon 30 jours"
  icon: 'mdi:flash'
```

I try different request (the FROM clause seems very strange) but I always get this error and no sensor are created.

Note: the working request in InfluxDB is the following:

`SELECT mean("value") AS "mean_value" FROM "hadb"."autogen"."℃" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "entity_id"='temperature_salon' GROUP BY time(:interval:) FILL(null)`

I try with from clause: FROM "hadb"."autogen"."℃" without success

Any help will be greatly appreciated.

**Comment by jmcollin78** [comment]
With this request:
```
service: pyscript.influxdb_query_to_entity
data:
  database: hadb
  query: >-
    SELECT mean("value") FROM "hadb"."autogen"."°C" WHERE time > now() - 30d
    AND "entity_id"="temperature_salon"
    GROUP BY time(30m) FILL(none)
  key_field_name: time
  value_field_name: mean
  entity_id: sensor.temperature_salon_30j
  unit_of_measurement: "°C"
  friendly_name: "Température salon 30 jours"
  icon: 'mdi:flash'
```

The error is the same:
```
2022-01-30 23:43:11 ERROR (MainThread) [custom_components.pyscript.apps.influxdb_query_to_entity.influxdb_query_to_entity] Exception in <apps.influxdb_query_to_entity.influxdb_query_to_entity> line 133:
        state.set(entity_id, value=lastPoint, new_attributes=attributes)
                                   ^
NameError: name 'lastPoint' is not defined
```

**Comment by jmcollin78** [comment]
Ok, I think I've got the problem. The collection in influxDb "hadb"."autogen"."°C" doesn't exists. It's name is "℃" (in one character) !.
Yes it does exists.
So this error just means "there is no value found". Maybe in a futur evolution a more comprehensive message will be a good think.

**Comment by markcocker** [comment]
@jmcollin78 It may be a valid scenario for the query to return an empty result set, so I'm cautious about pushing out a message in that situation. I could just ignore updating the entity, as in pull request #3, or clear out the entity value,

**Comment by jmcollin78** [comment]
Yes maybe PR #3 is a good think. Up to you to see that, I don't have so much background to have a valuable opinion.

My purpose was to put a clear message on the log that says "No data collected from <the request>" (example) and not just an obscur "NameError: name 'lastPoint' is not defined".

**Comment by jmcollin78** [comment]
I've added a comment in the PR #3 . We can close this point.
